name: "Comprueba texto temas"

on:
  push:
    paths:
      - 'temas/*.md'
      - 'problemas/*.md'
      - 'README.md'
      - 'words.dic'
  pull_request:
    paths:
      - 'temas/*.md'
      - 'problemas/*.md'
      - 'README.md'
      - 'words.dic'

jobs:
  Ortografia:
    runs-on: ubuntu-latest

    steps:
      - name: Prerrequisites
        run: sudo apt-get update && sudo apt-get install -y libtext-hunspell-perl autopoint
      - name: Checkout
        uses: actions/checkout@v2
      - name: Instala módulos
        run: sudo cpan Test::Text Tap::Harness
      - name: Ejecuta los tests
        run: |
          curl -s https://raw.githubusercontent.com/JJ/Test-Text/master/data/Spanish.aff -o Spanish.aff
          curl -s https://raw.githubusercontent.com/SublimeText/Dictionaries/master/Spanish.dic -o Spanish.dic
          rm proyectos.md asistentes.md # No nos interesan
          perl -MTAP::Harness -e 'use utf8; my $harness = TAP::Harness->new( { verbosity => 0} ); die "FAIL" if $harness->runtests( "t/just_check.t" )->failed;'

